### PR TITLE
Unraid-View v0.1

### PR DESCRIPTION
**Pull request by noodlemctwoodle**
Initail release.

Version 0.1
 - Initial view, responsive for both desktops and mobile devices.
 - Glances container support
 - Glances Home Assistant Integration
 - Added swipe card for docker containers
 - UnRAID-API added
 - Container Support
 - Added SNMP [config](https://github.com/noodlemctwoodle/homeassistant/blob/b2b1bed306b16d1366f25835d2840cea42f72352/packages/ha-core/areas/cabinet/devices/unraid/unraid_monitoring.yaml#L36)
 - combined disk usage into swipe card
 - Added HDD temperatures to temperatures swipe-card
 - Added LAN Throughput bar graph to resources swipe-card
 - Removed Tap actions on mini-graph-card and bar-card
 - Fixed graph height issue on swipe-card
 - Added bullets to swipe card and removed progress bar
 - Fixed template issue on 'Array Usage' when Home Assistant gets value of unavailable or none
 - Fixed issue with bar-card border radius
 - Fixed Mini-Graph-Card line colours
 - Fixed Font Size Bar-Card Colour overlap issue

### CODE REVIEW

**Comment by noodlemctwoodle** [comment]
Updated bar-card which was a major change, now need to fix the add-on layout 👎

**Comment by Klumpke** [comment]
Yes, i had the same issue with the printer addon. But the documentation of the bar card is very good

**Comment by Klumpke** [comment]
Would it be possible to change the path of the addon in the Git repo to "more_page/unraid_view " instead of "addons/unraid_view"?

**Comment by noodlemctwoodle** [comment]
Sure, when I push my next commit I'll make sure it's in the updated path.

**Pull request merged**
